# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe9586c7687d5806e1e6d9c5c134be4405fb59f9931045ce52ef04891f183142c33bab5f4d57c16b783b7664f084f743be95d7cdfa17a9c7a24d9ddabba6a28a

test:
  secret_key_base: 63219344b9c9248c48b77dc13cf7d65e26241276c0c8d62d068d54b0df5661ae7baea5a5548659befa89c84e6f1aef9248d423e38599831c69ff4ac94b38513a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
